# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: submission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='submission.proto',
  package='cpdash',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10submission.proto\x12\x06\x63pdash\"#\n\x11SubmissionRequest\x12\x0e\n\x06handle\x18\x01 \x01(\t\"\x97\x01\n\x0fSubmissionReply\x12\x0e\n\x06handle\x18\x01 \x01(\t\x12\x12\n\ncontest_id\x18\x02 \x01(\x05\x12\x15\n\rproblem_index\x18\x03 \x01(\t\x12\x10\n\x08sub_time\x18\x04 \x01(\x05\x12\x0f\n\x07verdict\x18\x05 \x01(\t\x12\x16\n\x0eproblem_rating\x18\x06 \x01(\x05\x12\x0e\n\x06status\x18\x07 \x01(\t2]\n\x11\x43odeforcesService\x12H\n\x0eGetSubmissions\x12\x19.cpdash.SubmissionRequest\x1a\x17.cpdash.SubmissionReply\"\x00\x30\x01\x62\x06proto3'
)




_SUBMISSIONREQUEST = _descriptor.Descriptor(
  name='SubmissionRequest',
  full_name='cpdash.SubmissionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle', full_name='cpdash.SubmissionRequest.handle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=63,
)


_SUBMISSIONREPLY = _descriptor.Descriptor(
  name='SubmissionReply',
  full_name='cpdash.SubmissionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle', full_name='cpdash.SubmissionReply.handle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contest_id', full_name='cpdash.SubmissionReply.contest_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='problem_index', full_name='cpdash.SubmissionReply.problem_index', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub_time', full_name='cpdash.SubmissionReply.sub_time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verdict', full_name='cpdash.SubmissionReply.verdict', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='problem_rating', full_name='cpdash.SubmissionReply.problem_rating', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='cpdash.SubmissionReply.status', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['SubmissionRequest'] = _SUBMISSIONREQUEST
DESCRIPTOR.message_types_by_name['SubmissionReply'] = _SUBMISSIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmissionRequest = _reflection.GeneratedProtocolMessageType('SubmissionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMISSIONREQUEST,
  '__module__' : 'submission_pb2'
  # @@protoc_insertion_point(class_scope:cpdash.SubmissionRequest)
  })
_sym_db.RegisterMessage(SubmissionRequest)

SubmissionReply = _reflection.GeneratedProtocolMessageType('SubmissionReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBMISSIONREPLY,
  '__module__' : 'submission_pb2'
  # @@protoc_insertion_point(class_scope:cpdash.SubmissionReply)
  })
_sym_db.RegisterMessage(SubmissionReply)



_CODEFORCESSERVICE = _descriptor.ServiceDescriptor(
  name='CodeforcesService',
  full_name='cpdash.CodeforcesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=219,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSubmissions',
    full_name='cpdash.CodeforcesService.GetSubmissions',
    index=0,
    containing_service=None,
    input_type=_SUBMISSIONREQUEST,
    output_type=_SUBMISSIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CODEFORCESSERVICE)

DESCRIPTOR.services_by_name['CodeforcesService'] = _CODEFORCESSERVICE

# @@protoc_insertion_point(module_scope)
