# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import submission_pb2 as submission__pb2


class CodeforcesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSubmissions = channel.unary_stream(
                '/cpdash.CodeforcesService/GetSubmissions',
                request_serializer=submission__pb2.SubmissionRequest.SerializeToString,
                response_deserializer=submission__pb2.SubmissionReply.FromString,
                )


class CodeforcesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSubmissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeforcesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSubmissions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSubmissions,
                    request_deserializer=submission__pb2.SubmissionRequest.FromString,
                    response_serializer=submission__pb2.SubmissionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cpdash.CodeforcesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CodeforcesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSubmissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cpdash.CodeforcesService/GetSubmissions',
            submission__pb2.SubmissionRequest.SerializeToString,
            submission__pb2.SubmissionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
